FROM debian:10.1
COPY test_suites_421 /test_suites_421
COPY dev-requirements.txt /dev-requirements.txt
RUN apt-get update && \
    apt-get install -y git python3 python3-pip gcc libcurl4-openssl-dev libssl-dev wget && \
    git clone --depth 1 --branch v4.2.1-dbaas-testing https://github.com/mongodb/mongo.git && \
    pip3 install --user -r /mongo/etc/pip/dev-requirements.txt && \
    pip3 install --user dnspython==1.16.0 && \
    cp /test_suites_421/* /mongo/buildscripts/resmokeconfig/suites && \
    wget https://downloads.mongodb.org/linux/mongodb-shell-linux-x86_64-debian10-4.2.1.tgz && \
    tar xzf mongodb-shell-linux-x86_64-debian10-4.2.1.tgz && \
    rm -rf /var/lib/apt/lists/* /tmp/* /mongodb-shell-linux-x86_64-debian10-4.2.1.tgz
COPY entrypoint.sh /entrypoint.sh
ENV m='/mongodb-linux-x86_64-debian10-4.2.1/bin/mongo'
ADD https://s3.amazonaws.com/rds-downloads/rds-ca-2019-root.pem /usr/local/share/ca-certificates/rds-ca-2019-root.crt
RUN update-ca-certificates
RUN ln -s /usr/bin/python3 /usr/bin/python && \
    ln -s /usr/bin/pip3 /usr/bin/pip
ENTRYPOINT ["/entrypoint.sh"]
