FROM debian:9.2
ARG branch
ARG mongoshell_package
ARG version
RUN apt-get update && \
    apt-get install -y git python2.7 python-pip gcc libcurl4-openssl-dev libssl-dev wget && \
    git clone --depth 1 --branch $branch https://github.com/mongodb/mongo.git && \
    pip install --user -r /mongo/buildscripts/requirements.txt && \
    pip install --user dnspython==1.16.0 && \
    wget https://downloads.mongodb.org/linux/mongodb-shell-linux-x86_64-$mongoshell_package.tgz && \
    tar xzf mongodb-shell-linux-x86_64-$mongoshell_package.tgz && \
    rm -rf /var/lib/apt/lists/* /tmp/* /mongodb-shell-linux-x86_64-$mongoshell_package.tgz
COPY entrypoint.sh /entrypoint.sh
COPY test_suites/$version/* /mongo/buildscripts/resmokeconfig/suites/
ENV m=/mongodb-linux-x86_64-$mongoshell_package/bin/mongo
ENV command="resmoke.py"
ADD https://s3.amazonaws.com/rds-downloads/rds-ca-2019-root.pem /usr/local/share/ca-certificates/rds-ca-2019-root.crt
RUN update-ca-certificates
ENTRYPOINT ["/entrypoint.sh"]
